---
title: "566 HW3 Maps"
author: "Matt Houtz"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---


```{r}
library("tidyverse")
library("leaflet")
```

```{r}
#Read in player data
players <- read.csv("C:/Users/matth/Documents/Grad School/Spring 2022/STAA 566/Data/pl_2020.csv")
country.counts <- table(players$Country)
country.df <- as.data.frame(country.counts)
colnames(country.df) <- c('Country', 'Count')

#Read in Lat/Long data
lat.lon <- read.csv("C:/Users/matth/Documents/Grad School/Spring 2022/STAA 566/Data/Country Coordinates.csv")

#Merge data sets to put latitude and longitude with counts
countries <- merge(country.df, lat.lon, by="Country")

#Create Hover Data
labs <- lapply(seq(nrow(countries)), 
               function(i) {
  paste0( "", as.character(countries[i, "Country"]), '<br>',
         "Number of Players in PL: ", as.character(countries[i, "Count"]),'' ) 
})

class(labs)
```

```{r}
countries %>% leaflet() %>% 
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "Street Map") %>%
  addProviderTiles(providers$OpenTopoMap, group = "Topograph") %>%
  addLayersControl(baseGroups = c("Street Map", "Topograph")) %>%
  addAwesomeMarkers(label = ~lapply(labs, htmltools::HTML)) %>%
  setView(lat = 23.1627859, lng = -42.545339, zoom = 2) %>%
  addMiniMap(
    toggleDisplay = TRUE,
    tiles = providers$Stamen.TonerLite
    )
```



